### ISSUE TITLE
Arrays not shown in visualization

### ISSUE THREAD

**Issue by meghaagr13** [pgbovine/opt-cpp-backend#61] opened 2017-07-26 20:03 UTC
In the following code the array is not visualized .
int main()
{
 int n=5;
 int arr[n];
 for(int i=0;i<n;i++)
  printf("%d",i);
}

**Comment by divyanshsinghvi** [comment] 2017-07-27 04:23
https://goo.gl/fzb6At
A link to the above code where it's not rendering the arrays. Infact the vgtrace is not showing up arrays possibly missing up something in hacked valgrind code only.

**Comment by pgbovine** [comment] 2017-07-29 02:54
yep, this is a duplicate of #44 -- thanks for reporting!

**Closed by pgbovine** 2017-07-29 02:54 UTC
